# 使用更新、更稳定的 Bun 版本
FROM oven/bun:1.1
WORKDIR /app
# 复制一个临时的 package.json 来安装bun-types
COPY package.json bun.lockb* ./
RUN bun install

# 添加启动脚本
COPY start-dev.sh ./
RUN chmod +x start-dev.sh

ENTRYPOINT []
CMD ["/bin/sh", "./start-dev.sh"]
