services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5678}:${BACKEND_PORT:-5678}"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/tododb
      NODE_ENV: production
      PORT: ${BACKEND_PORT:-5678}

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-4567}:${FRONTEND_PORT:-4567}"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      PORT: ${FRONTEND_PORT:-4567}
      BACKEND_PORT: ${BACKEND_PORT:-5678}

volumes:
  postgres_data:
