name: Deploy to AWS ECS

on:
  push:
    branches: [ release ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (AK/SK)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Normalize inputs
        env:
          ECR_REPOSITORY_RAW: ${{ secrets.ECR_REPOSITORY }}
          CLUSTER_RAW: ${{ secrets.ECS_CLUSTER_NAME }}
          SVC_BACKEND_RAW: ${{ secrets.ECS_BACKEND_SERVICE_NAME }}
          SVC_FRONTEND_RAW: ${{ secrets.ECS_FRONTEND_SERVICE_NAME }}
        run: |
          python3 - <<'PY'
          import os
          def norm(s: str) -> str:
              return s.replace('\r','').strip().strip('"').strip("'")
          envs = {
              'ECR_REPOSITORY_TRIM': norm(os.getenv('ECR_REPOSITORY_RAW','')),
              'ECS_CLUSTER_TRIM': norm(os.getenv('CLUSTER_RAW','')),
              'ECS_BACKEND_SERVICE_TRIM': norm(os.getenv('SVC_BACKEND_RAW','')),
              'ECS_FRONTEND_SERVICE_TRIM': norm(os.getenv('SVC_FRONTEND_RAW','')),
          }
          with open(os.environ['GITHUB_ENV'],'a') as f:
              for k,v in envs.items():
                  f.write(f"{k}={v}\n")
          PY

      - name: Compute image URIs
        run: |
          ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          BACKEND_TAG="backend-${{ github.sha }}"
          FRONTEND_TAG="frontend-${{ github.sha }}"
          echo "BACKEND_IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY_TRIM:$BACKEND_TAG" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY_TRIM:$FRONTEND_TAG" >> $GITHUB_ENV

      - name: Build and push backend
        run: |
          docker build -t "$BACKEND_IMAGE_URI" -f server/Dockerfile ./server
          docker push "$BACKEND_IMAGE_URI"

      - name: Build and push frontend
        run: |
          docker build -t "$FRONTEND_IMAGE_URI" -f client/Dockerfile ./client
          docker push "$FRONTEND_IMAGE_URI"

      - name: Render task defs (backend)
        run: |
          sed -i "s|ACCOUNT_ID|${{ secrets.AWS_ACCOUNT_ID }}|g" aws/task-definition-backend.json
          sed -i "s|REGION|${{ secrets.AWS_REGION }}|g" aws/task-definition-backend.json
          sed -i "s|REPOSITORY_NAME|$ECR_REPOSITORY_TRIM|g" aws/task-definition-backend.json
          sed -i "s|IMAGE_TAG|${{ github.sha }}|g" aws/task-definition-backend.json

      - name: Render task defs (frontend)
        run: |
          sed -i "s|ACCOUNT_ID|${{ secrets.AWS_ACCOUNT_ID }}|g" aws/task-definition-frontend.json
          sed -i "s|REGION|${{ secrets.AWS_REGION }}|g" aws/task-definition-frontend.json
          sed -i "s|REPOSITORY_NAME|$ECR_REPOSITORY_TRIM|g" aws/task-definition-frontend.json
          sed -i "s|IMAGE_TAG|${{ github.sha }}|g" aws/task-definition-frontend.json

      - name: Register & update backend service
        run: |
          aws ecs register-task-definition --cli-input-json file://aws/task-definition-backend.json >/dev/null
          aws ecs update-service --cluster "$ECS_CLUSTER_TRIM" --service "$ECS_BACKEND_SERVICE_TRIM" --task-definition todo-backend >/dev/null

      - name: Register & update frontend service
        run: |
          aws ecs register-task-definition --cli-input-json file://aws/task-definition-frontend.json >/dev/null
          aws ecs update-service --cluster "$ECS_CLUSTER_TRIM" --service "$ECS_FRONTEND_SERVICE_TRIM" --task-definition todo-frontend >/dev/null

      - name: Scale services to 1 (first deploy)
        run: |
          aws ecs update-service --cluster "$ECS_CLUSTER_TRIM" --service "$ECS_BACKEND_SERVICE_TRIM" --desired-count 1 >/dev/null
          aws ecs update-service --cluster "$ECS_CLUSTER_TRIM" --service "$ECS_FRONTEND_SERVICE_TRIM" --desired-count 1 >/dev/null


